# Generated by Django 3.2.12 on 2022-07-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash2o_app', '0003_refill_point_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
