# Generated by Django 3.2.12 on 2022-07-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash2o_app', '0005_alter_container_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill_point',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refill_point',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
