export default {
  HOME: 'HOME',
  REWARDS: 'REWARDS',
  LEADERBOARDS: 'LEADERBOARDS',
  INFO: 'INFO',
  ADDLOG: 'ADDLOG',
  USERLOGS: 'USERLOG',
  REFILL: 'REFILL',
  REPORT: 'REPORT',
  ABOUTUS: 'ABOUTUS',
  USERPROFILE: 'USERPROFILE',
};
