export const brandDropdownData = [
  {label: 'A&W', value: '1'},
  {label: 'Harveys', value: '2'},
  {label: 'KFC', value: '3'},
  {label: 'McDonald', value: '4'},
  {label: 'Pizza Pizza', value: '5'},
  {label: 'Prostea', value: '6'},
  {label: 'Starbucks', value: '7'},
  {label: 'Taco Bell', value: '8'},
  {label: 'Tim Hortons', value: '9'},
  {label: 'Wendy', value: '10'},
  {label: 'Others', value: '11'},
];

export const categoryDropdownData = [
  {label: 'Americano', value: '1'},
  {label: 'Black Coffee', value: '2'},
  {label: 'Bubble Tea', value: '3'},
  {label: 'Cappuccino', value: '4'},
  {label: 'Cortado', value: '5'},
  {label: 'Doppio', value: '6'},
  {label: 'Espresso', value: '7'},
  {label: 'Flat white', value: '8'},
  {label: 'Fruit Juices', value: '9'},
  {label: 'Latte', value: '10'},
  {label: 'Macchiato', value: '11'},
  {label: 'Milkshakes', value: '12'},
  {label: 'Mocha', value: '13'},
  {label: 'Softdrink ', value: '14'},
  {label: 'Water ', value: '15'},
  {label: 'Others', value: '16'},
];

export const refillLocationsData = [
  {
    ID: 1,
    Location: 'Leddy Library - East',
    Description: 'First floor - at the stairs door',
    Latitude: 42.307834,
    Longitude: -83.06789,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 2,
    Location: 'Leddy Library - East',
    Description: 'Ground floor - at the stairs door',
    Latitude: 42.307834,
    Longitude: -83.06789,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 3,
    Location: 'Leddy Library - East',
    Description: 'Second floor - at the stairs door',
    Latitude: 42.307834,
    Longitude: -83.06789,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 4,
    Location: 'Leddy Library - East',
    Description: 'Third floor - at the stairs door',
    Latitude: 42.307834,
    Longitude: -83.06789,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 5,
    Location: 'Leddy Library - West',
    Description: 'First floor - at the elevators',
    Latitude: 42.307742,
    Longitude: -83.068573,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 6,
    Location: 'Leddy Library - West',
    Description: 'Ground floor - at the elevators',
    Latitude: 42.307742,
    Longitude: -83.068573,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 7,
    Location: 'Leddy Library - West',
    Description: 'Second floor - at the elevators',
    Latitude: 42.307742,
    Longitude: -83.068573,
    Fountain: 'Yes',
    'Refill station': 'No',
  },
  {
    ID: 8,
    Location: 'CAW - Student Center',
    Description: 'Ground floor - at the wall garden',
    Latitude: 42.306471,
    Longitude: -83.06842,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 9,
    Location: 'CAW - Student Center',
    Description: 'Ground floor - at the wall garden',
    Latitude: 42.306471,
    Longitude: -83.06842,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 10,
    Location: 'CAW - Student Center',
    Description: 'First floor - at health services',
    Latitude: 42.306471,
    Longitude: -83.06842,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 11,
    Location: 'Essex Hall - South',
    Description: 'Ground Floor - at front door',
    Latitude: 42.305188,
    Longitude: -83.066841,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 12,
    Location: 'Essex Hall - South',
    Description: 'Ground floor -  at room no 121',
    Latitude: 42.304923,
    Longitude: -83.066675,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 13,
    Location: 'Essex Hall - Norht',
    Description: 'Ground floor - at front door ',
    Latitude: 42.305521,
    Longitude: -83.067067,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 14,
    Location: 'UoW Welcome Center',
    Description: 'at the front desk',
    Latitude: 42.304609,
    Longitude: -83.065436,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 15,
    Location: 'Dillon Hall',
    Description: 'Ground floor -  at the stairs',
    Latitude: 42.306463,
    Longitude: -83.067714,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 16,
    Location: 'Dillon Hall',
    Description: 'First floor - at the stairs',
    Latitude: 42.306463,
    Longitude: -83.067714,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 17,
    Location: 'Chrysler Hall - North',
    Description: 'Cashiers Office',
    Latitude: 42.306463,
    Longitude: -83.067714,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 18,
    Location: 'Toldo building',
    Description: 'Near Starbucks',
    Latitude: 42.306536,
    Longitude: -83.065486,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 19,
    Location: 'Joyce Enterprenuership Center',
    Description: 'Near the offices',
    Latitude: 42.304442,
    Longitude: -83.063468,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 20,
    Location: 'E.D. Lumley Center for Engineering Innovation',
    Description: 'Ground floor - at tim hortons',
    Latitude: 42.304677,
    Longitude: -83.062464,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 21,
    Location: 'E.D. Lumley Center for Engineering Innovation',
    Description: 'First floor - at the CS lab',
    Latitude: 42.304736,
    Longitude: -83.062168,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 22,
    Location: 'Laurier Hall - International Student Center',
    Description: 'First floor - at the front desk ',
    Latitude: 42.304674,
    Longitude: -83.067774,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
  {
    ID: 23,
    Location: 'Toldo Lancer Center',
    Description: 'Near the badminton court',
    Latitude: 42.299007,
    Longitude: -83.061377,
    Fountain: 'Yes',
    'Refill station': 'Yes',
  },
];

export const couponData = [
  {
    title: 'Amazon Gift Card',
    price: '$15CAD',
    info: ['Validity : 7 days', 'Single use', 'Available on limited items*'],
    button: {title: 'Reedeem Now(1000 points)', icon: 'lock-open'},
    color: '#f59042',
  },
  {
    title: 'Walmart Limited Offer',
    price: '20% OFF',
    info: ['Single Use only', 'Valid until (13th August)', 'On All items*'],
    button: {title: 'Redeem Now(2000 points)', icon: 'lock-open'},
    color: '#2561c2',
  },
  {
    title: 'Tim Hortons ',
    price: '$3 CAD',
    info: ['1 User', 'Double Double', 'Get it free on puchase of $5 or more*'],
    button: {title: 'Redeem Now(1500 points)', icon: 'lock-open'},
    color: '#c22525',
  },
  {
    title: 'Pizza Pizza',
    price: 'Free Delivery',
    info: ['30-day', 'Minimum Purchase $10', 'Get Free delivery for a month!!'],
    button: {title: 'Redeem Now(5000 points)', icon: 'lock-open'},
    color: '#c27425',
  },
  {
    title: 'UBER Ride',
    price: '50% Discount',
    info: ['Max 3 Passengers', 'Valid till 1 Sept 22'],
    button: {title: 'Redeem Now(500 points)', icon: 'lock-open'},
    color: '#c2c92c',
  },
];
